### ISSUE TITLE
HELP approach to minimum data consumption and low cost

### ISSUE THREAD

**Issue by danilomna** [mobizt/Firebase-ESP8266#110]
Hi @mobizt 

One more question:

Once Firebase charges for data download, what is the best approach to use downloading minimum data as possible? (so it can become expensive over time with thousand of devices).

Wich one uses more data download,  Stream or Stream Callback methods?
Which one is better?

best regards, 
Danilo

**Comment by mobizt** [comment]
No difference in network data consumption between loop reading the stream and callback.

You need to design your database to minimize the network data usage.  The node that being monitor its changes should be the top level child of the stream path (parent). 

Use the short node name, integer instead of string or boolean to reduce the payload data,.  

Don't get or set data too frequently, every 1 minute is enough.

Free 1 GB quota limit per month is enough for few devices or tenth of devices depends on your database design and the frequency of acquire/retrieve data.
