### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ChrisGy** [mobizt/Firebase-ESP8266#112]
According to a comment in [FirebaseESP8266.h](https://github.com/mobizt/Firebase-ESP8266/blob/master/src/FirebaseESP8266.h), setStreamCallback must be called _before_ Firebase.beginStream(). In the example [Stream_Callback](https://github.com/mobizt/Firebase-ESP8266/tree/master/examples/Stream_callback) however, setStreamCallback was called _after_ .beginStream(). 
What is the ideal, to prevent any problems?

**Comment by mobizt** [comment]
The results from the **setStreamCallback** called before **beginStream** and the **setStreamCallback** called after **beginStream** are the same.

When **beginStream** called without **readStream** or **setStreamCallback**, the stream data will stored in the internal buffer of Firebase Data object and available to read later. 

User can call **readStream**  later in loop to read the available stream which is the same as user calls the **setStreamCallback** later (in setup) because the **setStreamCallback** will call **readStream** internally and repeatedly in the schedule task.

You can follow the method used in the example.

The recommendation in function description about this in the header file need to be updated or removed.
