### ISSUE TITLE
Integration with Firestore?

### ISSUE THREAD

**Issue by BorjanKalinoski** [mobizt/Firebase-ESP8266#126]
I was wondering if there will be integration in this library with Firestore anytime soon. I know that it is possible to send and receive data from Firestore using the REST API, but I am mostly interested in listening to data changes in Firestore, just like the Stream example in this library for the Real-Time database.

So my question is is there a plan to integrate this feature in the near future?

Is there a possibility for me to wrap around the REST API and make a Stream-like feature? I have been lurking on forums and google for a few days and i just can't find any example of how to implement this, maybe I just need learn and search more.

I know there are workarounds like using a web server or cloud functions, but I am interested in direct communication between Firestore and ESP.

Best Regards,
Borjan

**Comment by mobizt** [comment]
The Cloud Firestore supports the REST API unless stream like feature are not available due to poor performance and Firebase team decided to remove this feature.

The only possible method that suitable for no Firebase SDK installation is the RPC (gRPC) which currently available in embedded device.

The other problem is database secret can't use in the Cloud Firestore, the auth or custom token is required and need the SSL/TLS library for key encryption and signing.  This can be done in ESP32 with mbed TLS  which can't do in ESP8266 with BearSSL.

Then Cloud Firestore with realtime feature (using gRPC) is not possible in ESP8266.
