### ISSUE TITLE
HTTP Code -4 when data is streaming correctly

### ISSUE THREAD

**Issue by arlucio** [mobizt/Firebase-ESP8266#127]
In my code I have 3 FirebaseData variables firebaseDataStream, firebaseDataSetter, firebaseDataReader, that are used only for streaming, setting and reading data.

For testing, I'm printing the .httpCode() every loop. With the system working without any problem, I always get: 

```
HTTP Code Stream: -4
HTTP Code Reader: 200
HTTP Code Setter: 200
```

This happens with the streaming 100% working correctly.

Is this the expected behavior? Should the httpCode from the FirebaseData that is streaming data be -4 when it is working normally? 

When I turn off my WiFi and lose connection, the HTTP Code from all the FirebaseData goes, as expected, to -5 (to clarify, the streaming one goes to -5 automatically, and for the other 2 I have to respectively try to read/set some data so it goes to -5). When connected again it all goes back to -4, 200, 200.

This don't cause any problem for my code, but I'm using (firebaseDataStream.httpCode() == -4) as the expected condition for when the stream is working normally, and (== 200) for the other 2.

**Comment by mobizt** [comment]
The **httpCode** function returns the positive value from HTTP response and negative value from client or operation errors

Check the error code [here](https://github.com/mobizt/Firebase-ESP8266/blob/master/src/FirebaseESP8266HTTPClient.h#L97) 

The value -4 means, the tcp client can't establish the server connection which can be happened when new connection required due to timeout or the single Firebase Data object used for both stream and  store/restore operations. 

During stream operation, you should determine the stream connection status from **streamTimeout()** function instead.
