### ISSUE TITLE
Cannot get data : errorReason() is empty

### ISSUE THREAD

**Issue by pgrenon1** [mobizt/Firebase-ESP8266#133]
Hi, I'm trying to get all the data contained in the "/logs" node from this database:
![image](https://user-images.githubusercontent.com/35233201/92335012-e3f17400-f060-11ea-9855-9f0443d7accf.png)

The code I am running looks like this:
`
    Serial.println("GET");

    if (Firebase.get(firebaseData, "/logs"))
    {
        Serial.println("PASSED");
        Serial.println("PATH: " + firebaseData.dataPath());
        Serial.println("TYPE: " + firebaseData.dataType());
    }
    else
    {
        Serial.println("FAILED");
        Serial.println("REASON: " + firebaseData.errorReason());
        Serial.println("------------------------------------");
        Serial.println();
    }`

And the result looks like this:
![image](https://user-images.githubusercontent.com/35233201/92335127-10f25680-f062-11ea-8c1b-2109bf437f18.png)

How can I read all the data in "/logs"?

Thanks in advance

**Comment by mobizt** [comment]
Data under logs is too large, redesign your data structure to get the exactly data you want instead of get all data from your database at once like this.

You device has a limited memory that you should be known and take in to account when you want to work with it.

You can also increase the [rx buffer size](https://github.com/mobizt/Firebase-ESP8266/blob/master/examples/Basic/Basic.ino#L55) and set the [buffer response size](https://github.com/mobizt/Firebase-ESP8266/blob/master/examples/Basic/Basic.ino#L58) to increase the buffer to handle the larger data.
