### ISSUE TITLE
ENHANCEMENT: Self-help Firebase credential management and/or auto-create Firebase branch

### ISSUE THREAD

**Issue by sarkrui** [mobizt/Firebase-ESP8266#136]
**Is your feature request related to a problem? Please describe.**
The current situation is, `FIREBASE_HOST` and `FIREBASE_AUTH` are all hardcoded. This can be inconvenient if the prototype is to share as a gift and the receiver doesn't have access to the developer's Firebase account (I personally felt a bit sorry if I can always have the access to the Firebase account being used by the sent gifts). The receiver might not familiar with Arduino Programming, and so asking them to modify, compile and upload the firmware to the ESP can be a bit challenging. 

**Describe the solution you'd like**
- **Option 1**: Replicate something like [WiFIManager](https://github.com/tzapu/WiFiManager), the Wi-Fi credential isn't pre-coded in Sketch but stored in the SPI section of the flash (I'm not 100% sure); Furthermore, such a mechanism allows the WiFi settings to be swapped alter on without re-flashing the Sketch.

**Describe alternatives you've considered**
- **Option 2**: (This is, more or less, aimed for my [project: Light-Messenger](https://github.com/sarkrui/Light-Messenger)) Perhaps there could have a function can could easily create a `branch` for a pair or a set of ESP8266 devices (see topology below), to allow multiple branches to be set on the Firebase automatically. The auto-generated branch could be named according to the mac address of each ESP chip. This would allow more clones (Pair A and Pair B) to be appended under the same Firebase root. I am thinking if this is necessary to be implemented in the library.

```
--root

----[LAST_4_DIGI_MAC_ADDR_A]_[LAST_4_DIGI_MAC_ADDR_B]
------Pair_A
------Pair_B
------Pair_C

----branch_1
------Pair_A
------Pair_B
------Pair_C

(......)

----branch_XXX
------Pair_A
------Pair_B
------Pair_C

```
(N.B: All Pair A are using the same Sketch code, so are Pair B. Branches can be automatically managed and appended by the Firebase library.)

**Comment by mobizt** [comment]
Thank you for idea for improvement and congrats to your cool project.

The first option based on user requirements. 

Some users require the hard code of credentials due to it is private project and some users need the credential management when distribute the embedded device product  to their users.

This can be done in different way which requires other user interfaces companion apps which act the same way as the WiFi manager, Smart config and Bluetooth serial apps.

To add this feature to the device without credentials hard coding, it required the companion UI apps that can be transfer data from/to ESP8266 device which is out of this library scope.  

I will give you some guidelines about the credentials management and introduce the library which you can design your own web UI to interact directly with the device.

For letting your clients to initiate the ESP8266 device with the project name/URL and the database secret easily without to type these info manually and that info is unreadable for user, you can try the following.

Join the project name and database secret as one string and encode it with base64 algorithm then show that base64 encode string to user as QR code (in your app or sticker on your product) that allows the user to saved the image and scan it with other QR code apps.

User copy the basse64 decoded text from QR image and paste it to ESP8266 companion UI apps.

The ESP8266 device decodes the base64 encoded string and separate it to project name/URL and the database secret.

You can use [this my another library](https://github.com/mobizt/ESPForm) to make the web UI companion app with unlimited design (with any js and css libraries as jQuery and bootstrap) and the user input data can be saved and loaded to/from flash or SD card.

For option 2, the user data will be modified which may be unwanted by other users which their usages are different.
