### ISSUE TITLE
Reading and handling user input without significant delay

### ISSUE THREAD

**Issue by opp34** [mobizt/Firebase-ESP8266#159]
Good night,

first, I want to thank creator of the library – I tested few other libraries that try to handle firebase and at some point each of them failed (high memory usage, memory leak, regular exceptions). 

I’m working on the project that uses firebase to store settings, statistics etc. There is an android application that shows sensors’ readings and it’s used to set setpoints, limits or control items in manual mode. That information has to be forwarded to ESP8266. In some cases, it should come as soon as possible (mode, controls bits in manual mode) that there is no significant delay for the user; in other cases, it can be read once per 10 minutes or 1 hour (data for graphs, statistics). The issue is to have that without high data transfer, with low, stable ESP8266 cycle time and ESP8266 being up to date.
I tried the following settings:
1. Use basic commands, set and get. It causes high cycle time because every item is treated separately (high cycle time, above 1 second, up to 10 seconds).
2. Use JSON object, setJSON and getJSON. Cycle time is significantly decreased but still reading of most important data has to be done frequently which may increase data transfer. 
3. Use stream for settings that have to up to date. Cycle time is low, it’s triggered only when data is different so data transfer should be minimal. But as it was mentioned in one of other topics, sometimes stream callback is not triggered and ESP8266 may not be updated. 

Is there any other, better solution? Or am I doing something wrong? How did you solve such issues? Is there any other way to provide and handle user input without significant delay? One that I think of is to use stream but send a feedback to database that informs user that operation he performed was truly done. 

At this point I think I should use JSON objects in general, for important data (mode, control bits in manual mode) it has to be updated even 10 times per second (if that doesn’t cause database throttle and data transfer doesn’t go that high).

**Comment by mobizt** [comment]
You need to design and manage your workflow by known the constraints of your system.

The round trip time for HTTP request is more than TCP/UDP. You will never get 10 requests/second in data transfer.

The stream connection keeps the connection to stay alive as long as the client and server connected to internet. Any internet interruption will stop the stream and need to establish new connection.  Every new connection uses much time (almost a second) in asl/tls handshaking process. Any consequence connection will be faster as 0.2-0.3 second per request due to the keep alive mode connection (no more asl/tls handshaking required).

Due to the single core mcu, other user code tasks can delay the time for reading the stream data from rx buffer of the http client. If no new keep-alive event pushed from server in time within 40 seconds the stream connection will be closed and the timeout notified and resume the connection.

Based on your database design, I can't say anything more than redesign your database to be simply.

Permanent and large log data should be keep separately in another brance from the light and realtime status data. 

The realtime data should keep small and the update will not be faster than 4 times/sec due to the http round trip time mentioned above.

Your requirement may not suit for Firebase RTDB that implemented in limited resources device especially you have a large data to update.

Setting up your own TCP or UDP server is the best unless required server maintenance.

The MQTT is fast but not suitable for large payload and need to manage data storage separately.
