### ISSUE TITLE
[HELP] What is causing connection refused?

### ISSUE THREAD

**Issue by BorjanKalinoski** [mobizt/Firebase-ESP8266#167]
When i read a value from firebase, i have no problems. When i write to another path, using different FirebaseData and different FirebaseJsonData objects, i get a connection refused error. I had no issues with this few days ago, help  :) . 
Is my code a problem, is some firebase settings a problem, is it just the network?
![image](https://user-images.githubusercontent.com/37346995/98483311-689a7300-2207-11eb-8fdc-36ea06b2febb.png)

**Comment by mobizt** [comment]
It is because the SSL client can't connect to the server for some reason.
- The internet access issue due to WiFi AP, router and ISP
- The invalid or not existed host.  If you are hard code the **FIREBASE_HOST**, you may need to print out to check whether it's still correct or not. In some situation that the memory that this host name is stored is corrupted  from the memory allocation or improper handling and then the memory leaks.
