### ISSUE TITLE
Firebase events are missed or not detected

### ISSUE THREAD

**Issue by arunanil03** [mobizt/Firebase-ESP8266#177]
Firebase events are not getting detected , only when multiple fields are updates simultaneously , only one or maximum of two events will get detected when 4 to 5 fields are updated.

**To Reproduce**
1)  listen to a path having 4 to 5 branches
2) change all the 4 branches values at the same time 

**Expected behavior**
Only one or two changes will get detected

**Comment by mobizt** [comment]
When using the shared Firebase Data object for stream and other usagges i.e. normal operation to read and store data,
the stream will be interrupted to use in other tassks, the stream will be resumed (reconnection) after that normal usage was finished.

For the above case, you need to provide the free time for stream to listen to the server event data. The changes on the server at the streaming node path during the stream interruption will be missed.

To avoid this sitation, don't share the usagge of stream's Firebase Data object, use other Firebase Data object instead.

In addition, delay function used in the same loop block of readStream() will interrupt the stream operation, the server data changes may be missed.

More use of Firebase Data object at the same scope i.e more than 2 can leead to out of memory error as the most memory used in Firebase Data object is due to SSL client.

**Comment by arunanil03** [comment]
I am using the stream example provided with the library

**Comment by mobizt** [comment]
Even you change the few tens child nodes data simultaneously , the client will only  get few of them as this library uses the REST API  (http request/response) which not the tcp socket connection which can provide the callback handler to handle all multiple  the socket data.

**Comment by arunanil03** [comment]
Is there any solution for my requirement ?

**Comment by mobizt** [comment]
That's a limit on the mythology used, no solution. 
Google does not provide the socket connection for Firebase as in other client which relies on its SDK.

**Comment by mobizt** [comment]
Known the limitation and redesign your database.

**Comment by arunanil03** [comment]
when it comes to multiple field update, if i can implement a delay for each filed update  in my application, it can solve the problem right ?

**Comment by mobizt** [comment]
You should save the local changes (store it to json), and push theses changes as a JSON data at once.

**Comment by arunanil03** [comment]
OK ! will try that , thanks  ! @mobizt

**Comment by arunanil03** [comment]
i dont have any problem in receiving events in version 2.0.8 of the library
, i started the project with that version and now when i tried switching
it back to 2.0.8 from the latest version , now all the events are received
one after the other . and no event is missed

>

**Comment by mobizt** [comment]
I don't know what you said 2.0.8. There is no version 2.0.8.
