### ISSUE TITLE
Authenticate NodeMCU with custom token

### ISSUE THREAD

**Issue by NiteAx** [mobizt/Firebase-ESP8266#215]
I'm trying to authenticate my NodeMCU with my DB using a custom token. 
The NodeMCU sends a unique identifier (ex: mac address) to a Flask server, which mints a custom token using the Firebase Admin SDK. The token is returned to the NodeMCU, but from there i'm a little unclear on how to proceed. I've tested the example for authenticating using email&pass, works great. I looked at the example for using custom token, and it looks like the sketch requires service account credentials to mint its own token based on a specified uid. Is it possible to bypass this and authenticate using the token minted by the Flask server?

**Comment by mobizt** [comment]
The custom token is the custom claim signed  jwt token used to request the id token from the Google API's end point at identitytoolkit.googleapis.com.

With sign-in method, the id token will be generated.

This id token used in the authorization header when requesting the Firebase services.

Normally using the user provided token is not allowable in this library because the token needs to manage by the library itself for the flow of authentication process including checking and generation.

The only possible way is to edit the shared configuration, FirebaseConfig.

If your token that taken from your server is signed jwt, it can't use with this library.
if your token is id token, you can replace the id token generated in this library with

```cpp
if (Firebase.ready())
{
  config.signer.tokens.id_token = "your id token";
  config.signer.tokens.expires = time(nullptr) + 3600;
}

```
The above method works when the following credentials from your service account are defined.

```cpp
  auth.token.uid = "your custom id";
  config.api_key = API_KEY;
  config.service_account.data.client_email = FIREBASE_CLIENT_EMAIL;
  config.service_account.data.project_id = FIREBASE_PROJECT_ID;
  config.service_account.data.private_key = PRIVATE_KEY;
  config.database_url = DATABASE_URL;


```
