### ISSUE TITLE
how to retrieve timestamp

### ISSUE THREAD

**Issue by CR7Pacemaker** [mobizt/Firebase-ESP8266#31]
timestamp always give 2147483647 as it shows it as int data type,
although value pushed and set are correct but i want to retrieve it in nodemcu how to do that?
is there any long data type available?

**Comment by mobizt** [comment]
Thanks for addressing this.

Due to incorrect timestamp example, timestamp (Google's timestamp server value) is in millisecond and should read through **doubleData** which it is too large for integer.

Due to bug in Serial.print in Arduino, large value of double may print as ovf (overflow). 
I recommend to use **printf("%.0lf\n", firebaseData.doubleData());** for print timestamp in milliseconds.

I also update the library (v 2.1.6) to get timestamp in seconds which can read through **intData()** after you call **setTimestamp**.

The Timestamp example is updated to make proper printed timestamp value.  All other example sketches that print the double value also changed to use printf.

The library also fixed the invalid data type for large double may returns as int, please update.
