### ISSUE TITLE
getJSON returns unknown error

### ISSUE THREAD

**Issue by JoergTiedemann** [mobizt/Firebase-ESP8266#352]
Hi
I use the library with an ESP 8266 and a firebase realtime database to log sensor readings. Everything works well. But if I will read the logged values from the database using 
Firebase.getJSON(fbdo, "/Pumpenmonitor/pumpenloging")
where "/Pumpenmonitor/pumpenloging" is the node with the logging data, getJSON return false and errorReason contains "unknown error"
the database looks like the screenshot

![Screen](https://user-images.githubusercontent.com/6218573/212747874-96fdff1e-ed34-4b32-aebc-1805f66f56d0.png)

If I extend the path "/Pumpenmonitor/pumpenloging" with a valid subkey i.e. to "/Pumpenmonitor/pumpenloging/1673887956"
it works and getJSON return a valid dataset

What could be the reason or how can I iterate through the subnodes?

**Comment by mobizt** [comment]
When you want to get the large data, you need to set up the BearSSLreceive (rx) buffer size that big enough for your data otherwise the BearSSL can't decrypt the incomplete data and return nothing.

https://github.com/mobizt/Firebase-ESP8266/blob/e2e1d627a62300a3d2717b9b495a6fff98fc2463/examples/File/Flash/Flash.ino#L101
